matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    sudo: false
    # From https://goo.gl/XuEMpi GCP CD with travis
    env: PROTOC="${HOME}/protobuf/bin/protoc" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - os: osx
    # psutil fails to install on the default beta-xcode6.1
    osx_image: xcode6.4
    language: generic
    python: 2.7
    sudo: required
    env: PROTOC="${HOME}/protobuf/bin/protoc" PATH=$PATH:${HOME}/google-cloud-sdk/bin CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/protobuf
before_install:
- /bin/bash travis/install_protobuf.sh $TRAVIS_OS_NAME
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install libffi && git clone https://github.com/MacPython/terryfy && source terryfy/travis_tools.sh; get_python_environment macpython 2.7.11; fi
# We upgrade pip inside the virtualenv to avoid sudo here.
- pip install --upgrade virtualenv
- virtualenv ${HOME}/INSTALL
install:
- /bin/bash travis/install.sh
script:
  - source ${HOME}/INSTALL/bin/activate && if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then grr_run_tests --processes=2; else grr_run_tests --processes=2 --labels=client_action; fi && /bin/bash travis/deploy_to_gcs.sh
addons:
  apt:
    packages:
    - libffi-dev
    - libssl-dev
    - python-dev
    - prelink
